function varargout = show( this, varargin )

figureHandle = [];
axisHandle = [];
postcommands = '';
precommands = '';
ctrack = 1;
timestep = this.time;


trackplotOpt = {...
    '''Marker'',''.'',''LineStyle'',''None'',''Color'',[0 0 1]',...
    '''Marker'',''.'',''LineStyle'',''None'',''Color'',[1 0 0]',...
    '''Marker'',''.'',''LineStyle'',''None'',''Color'',[0 1 0]',...
    '''Marker'',''.'',''LineStyle'',''None'',''Color'',[1 0 1]',...
    '''Marker'',''.'',''LineStyle'',''None'',''Color'',[1 1 0]',...
    '''Marker'',''.'',''LineStyle'',''None'',''Color'',[0 0 1]',...
    '''Marker'',''.'',''LineStyle'',''None'',''Color'',[0 1 1]',...
    '''Marker'',''.'',''LineStyle'',''None'',''Color'',[0 0 0]',...
    '''Marker'',''o'',''LineStyle'',''None'',''Color'',[1 0 0]',...
    '''Marker'',''o'',''LineStyle'',''None'',''Color'',[0 1 0]',...
    '''Marker'',''o'',''LineStyle'',''None'',''Color'',[1 0 1]',...
    '''Marker'',''o'',''LineStyle'',''None'',''Color'',[1 1 0]',...
    '''Marker'',''o'',''LineStyle'',''None'',''Color'',[0 0 1]',...
    '''Marker'',''o'',''LineStyle'',''None'',''Color'',[0 1 1]',...
    '''Marker'',''o'',''LineStyle'',''None'',''Color'',[0 0 0]',...
    '''Marker'',''h'',''LineStyle'',''None'',''Color'',[1 0 0]',...
    '''Marker'',''h'',''LineStyle'',''None'',''Color'',[0 1 0]',...
    '''Marker'',''h'',''LineStyle'',''None'',''Color'',[1 0 1]',...
    '''Marker'',''h'',''LineStyle'',''None'',''Color'',[1 1 0]',...
    '''Marker'',''h'',''LineStyle'',''None'',''Color'',[0 0 1]',...
    '''Marker'',''h'',''LineStyle'',''None'',''Color'',[0 1 1]',...
    '''Marker'',''h'',''LineStyle'',''None'',''Color'',[0 0 0]',...
    '''Marker'',''p'',''LineStyle'',''None'',''Color'',[1 0 0]',...
    '''Marker'',''p'',''LineStyle'',''None'',''Color'',[0 1 0]',...
    '''Marker'',''p'',''LineStyle'',''None'',''Color'',[1 0 1]',...
    '''Marker'',''p'',''LineStyle'',''None'',''Color'',[1 1 0]',...
    '''Marker'',''p'',''LineStyle'',''None'',''Color'',[0 0 1]',...
    '''Marker'',''p'',''LineStyle'',''None'',''Color'',[0 1 1]',...
    '''Marker'',''p'',''LineStyle'',''None'',''Color'',[0 0 0]'...
    };

posttrackcommands = {''};
 
 obsplotOpt = {...
     {'''Marker'',''x'',''LineStyle'',''None'',''Color'',[0 1 0]'},...
     {'''Marker'',''x'',''LineStyle'',''None'',''Color'',[0 0 1]'},...
     {'''Marker'',''x'',''LineStyle'',''None'',''Color'',[1 0 0]'},...
     {'''Marker'',''x'',''LineStyle'',''None'',''Color'',[1 1 0]'},...
     {'''Marker'',''x'',''LineStyle'',''None'',''Color'',[0 0 1]'},...
     {'''Marker'',''x'',''LineStyle'',''None'',''Color'',[0 1 1]'},...
     {'''Marker'',''x'',''LineStyle'',''None'',''Color'',[0 0 0]'} };
     


nvarargin = length(varargin);
argnum = 1;
while argnum<=nvarargin
     if isa( lower(varargin{argnum}), 'char')
         switch lower(varargin{argnum})
             case {'axis'}
                 if argnum + 1 <= nvarargin
                     axisHandle = varargin{argnum+1};
                     argnum = argnum + 1;
                 end
             case {'figure'}
                 if argnum + 1 <= nvarargin
                     figureHandle = varargin{argnum+1};
                     argnum = argnum + 1;
                 end
             case {'postcommands'}
                 if argnum + 1 <= nvarargin
                     postcommands = varargin{argnum+1};
                     argnum = argnum + 1;
                 end
             case {'trackplotoptions'}
                 if argnum + 1 <= nvarargin
                     trackplotOpt = varargin{argnum+1};
                     argnum = argnum + 1;
                 end
             case {'obsplotoptions'}
                 if argnum + 1 <= nvarargin
                     obsplotOpt = varargin{argnum+1};
                     argnum = argnum + 1;
                 end
             case {'precommands'}
                 if argnum + 1 <= nvarargin
                     precommands = varargin{argnum+1};
                     argnum = argnum + 1;
                 end
             case {'time'}
                 if argnum + 1 <= nvarargin
                     timestep = varargin{argnum+1};
                     argnum = argnum + 1;
                 end
             case{'ctrackoff'}
                 ctrack = 0;
             otherwise
                 error('Wrong input string');
         end
     end
     argnum = argnum + 1;
end

plotOptCnt  = 1;
obsplotoptcnt = 1;
ptcnt = 1;% Post track counter

if isempty(axisHandle)
    if isempty(figureHandle)
        figureHandle = figure;
    end
    axisHandle = gca;
else
    if isempty(figureHandle)
        figureHandle = gcf;
    end
end

for cnt = 1:length(this.platforms)
   [axisHandle, figureHandle] =  this.platforms{cnt}.show( 'axis', axisHandle, ...
        'figure',figureHandle, ...
        'time', timestep,...
        'precommands', precommands,...
        'postcommands', postcommands,...
        'trackplotoptions', trackplotOpt{plotOptCnt},...
        'obsplotoptions', obsplotOpt{obsplotoptcnt},...
        'ctrack',ctrack...
        );
    plotOptCnt = plotOptCnt+1;
    obsplotoptcnt = obsplotoptcnt + 1;
    if plotOptCnt> length(trackplotOpt)
        plotOptCnt = 1;
    end
    if obsplotoptcnt > length( obsplotOpt )
        obsplotoptcnt = 1;
    end
end


if nargout>=1
     varargout{1} = axisHandle;
end
if nargout>=2
     varargout{2} = figureHandle;
end
